http://localhost:9200
--

--
POST /_analyze
{
    "tokenizer": "standard",
    "text": "I'm in the mood for drinking semi-dry red wine!"
}

--
POST /_analyze
{
    "tokenizer": "standard",
    "filter": ["lowercase"],
    "text": "I'm in the mood for drinking semi-dry red wine!"
}
